micronaut:
  application:
    name: protobuf
grpc:
  server:
    health:
      enabled: true
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    shipping:
      address: '0.0.0.0:8084'
      plaintext: true
      max-retry-attempts: 5


endpoints:
  all:
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
